### ISSUE TITLE
Sage 10 & Node >=12

### ISSUE THREAD

**Issue by jkananen** [steenbergen-design/trellis-action#11]
Roots / [Sage 10](https://github.com/roots/sage) is coming and uses `"node" : ">=12.0.0"`, but per this action's readme:

> We're using the alpine:3.9 docker image, so only NodeJS 10 is available.

Are there plans to update alpine / NodeJS the action to a newer version, or are there ways to work around this?

The deploy log currently reads:

```sh
  error @: The engine "node" is incompatible with this module. Expected version
  ">=12.0.0". Got "10.19.0"
```
Thanks!

**Comment by smpetrey** [comment]
It's a known issue. However, a fix is coming soon. This PR should be merged soon: https://github.com/steenbergen-design/trellis-action/pull/10

**Comment by jkananen** [comment]
Works with https://github.com/steenbergen-design/trellis-action/releases/tag/v1.0.2

Thanks, closing.
